version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: commitlens
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - .env.example

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# Homebrew tap for macOS/Linux users
brews:
  - repository:
      owner: alkowskey
      name: homebrew-tap
    homepage: https://github.com/alkowskey/commitlens
    description: "A lightweight CLI tool that tracks file changes with AI-powered summaries"
    license: MIT
    install: |
      bin.install "commitlens"
    test: |
      system "#{bin}/commitlens", "version"
